# Generated by Django 3.1.6 on 2021-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='school',
        ),
        migrations.AlterField(
            model_name='module',
            name='moduleCode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
