# Generated by Django 3.1.6 on 2021-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210228_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='typeOfStudent',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
