# Generated by Django 3.1.6 on 2021-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_typeofstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='typeOfStudent',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Tutee', 'Tutee')], max_length=10, verbose_name='Tutor/Tutee'),
        ),
    ]
