# Generated by Django 3.1.6 on 2021-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210308_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='typeOfStudent',
        ),
        migrations.AddField(
            model_name='listing',
            name='typeOfListing',
            field=models.CharField(choices=[('Providing', 'Providing'), ('Requesting', 'Requesting')], default='Providing', max_length=10, verbose_name='Providing/Requesting'),
            preserve_default=False,
        ),
    ]
