# Generated by Django 3.1.6 on 2021-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210309_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionsession',
            name='acceptOrder',
            field=models.IntegerField(default=0),
        ),
    ]
