# Generated by Django 3.1.6 on 2021-03-11 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210301_1215'),
        ('listings', '0006_tuitionsession_acceptorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionsession',
            old_name='acceptOrder',
            new_name='acceptOffer',
        ),
        migrations.AddField(
            model_name='tuitionsession',
            name='initiatedOffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
