# Generated by Django 3.1.6 on 2021-03-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210311_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionsession',
            name='acceptOffer',
        ),
        migrations.RemoveField(
            model_name='tuitionsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tuitionsession',
            name='initiatedOffer',
        ),
    ]
