# Generated by Django 3.1.6 on 2021-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210311_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionsession',
            name='acceptOffer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tuitionsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
