# Generated by Django 3.1.6 on 2021-03-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210311_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionsession',
            old_name='acceptOffer',
            new_name='offer',
        ),
    ]
