# Generated by Django 3.1.6 on 2021-03-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210312_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionsession',
            name='completed',
        ),
    ]
