# Generated by Django 3.1.6 on 2021-02-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3000)),
                ('rating', models.IntegerField()),
                ('reviewee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewee', to='users.profile')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='users.profile')),
                ('tuitionSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.tuitionsession')),
            ],
        ),
    ]
